# Generated by Django 4.2 on 2025-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_Picture',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
